/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package paneli;

import domen.Dnevnik;
import forme.FormaDnevnik;
import forme.GlavnaForma;
import java.awt.Window;
import java.time.LocalDate;
import java.util.List;
import kontroler.Kontroler;
import modeli.DnevnikTableModel;

/**
 *
 * @author Uros
 */
public class DnevniciPanel extends javax.swing.JPanel {

    private Window roditelj;

    /**
     * Creates new form DnevniciPanel
     */
    public DnevniciPanel(Window roditelj) {
        initComponents();
        this.roditelj = roditelj;

        popuniTabeluDnevnika(Kontroler.getInstanca().vratiDnevnike(null));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtPretraga = new javax.swing.JTextField();
        btnPretrazi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDnevnici = new javax.swing.JTable();
        btnKreiraj = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(800, 500));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Dnevnici");

        txtPretraga.setOpaque(true);
        txtPretraga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPretragaActionPerformed(evt);
            }
        });

        btnPretrazi.setText("Pretrazi");
        btnPretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretraziActionPerformed(evt);
            }
        });

        tblDnevnici.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDnevnici.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblDnevniciMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblDnevnici);

        btnKreiraj.setText("Kreiraj dnevnik");
        btnKreiraj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKreirajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPretrazi))
                    .addComponent(btnKreiraj)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 693, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPretrazi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnKreiraj)
                .addContainerGap(30, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretraziActionPerformed
        String[] kriterijum = txtPretraga.getText().toLowerCase().split(" ");
        popuniTabeluDnevnika(Kontroler.getInstanca().vratiDnevnike(kriterijum));
    }//GEN-LAST:event_btnPretraziActionPerformed

    private void btnKreirajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKreirajActionPerformed
        FormaDnevnik formaDnevnik = new FormaDnevnik((GlavnaForma) roditelj, null, true);
        formaDnevnik.setVisible(true);
    }//GEN-LAST:event_btnKreirajActionPerformed

    private void tblDnevniciMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDnevniciMousePressed
        Dnevnik dnevnik = (Dnevnik) tblDnevnici.getValueAt(tblDnevnici.getSelectedRow(), 0);

        FormaDnevnik formaDnevnik = new FormaDnevnik((GlavnaForma) roditelj, dnevnik, true);
        formaDnevnik.setVisible(true);
    }//GEN-LAST:event_tblDnevniciMousePressed

    private void txtPretragaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPretragaActionPerformed
        btnPretraziActionPerformed(evt);
    }//GEN-LAST:event_txtPretragaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKreiraj;
    private javax.swing.JButton btnPretrazi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDnevnici;
    private javax.swing.JTextField txtPretraga;
    // End of variables declaration//GEN-END:variables

    public void popuniTabeluDnevnika(List<Dnevnik> dnevnici) {
        tblDnevnici.setModel(new DnevnikTableModel(dnevnici));

        tblDnevnici.getColumnModel().getColumn(0).setMinWidth(0);
        tblDnevnici.getColumnModel().getColumn(0).setMaxWidth(0);
    }
}
