/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forme;

import domen.Dnevnik;
import domen.StavkaDnevnika;
import domen.Zadatak;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JDialog;
import kontroler.Kontroler;
import modeli.StavkaTableModel;

/**
 *
 * @author Uros
 */
public class FormaStavka extends javax.swing.JDialog {
    
    private Dnevnik dnevnik;
    private JDialog roditelj;

    /**
     * Creates new form FormaStavka
     */
    public FormaStavka(JDialog roditelj, Dnevnik dnevnik, boolean modal) {
        super(roditelj, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.dnevnik = dnevnik;
        this.roditelj = roditelj;
        
        popuniComboZadataka(Kontroler.getInstanca().vratiZadatke());
        comboZadaci.getModel().setSelectedItem(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        comboZadaci = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        btnDodaj = new javax.swing.JButton();
        spnTrajanje = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Zadatak:");

        comboZadaci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboZadaciActionPerformed(evt);
            }
        });

        jLabel2.setText("Trajanje:");

        btnDodaj.setText("Dodaj");
        btnDodaj.setEnabled(false);
        btnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajActionPerformed(evt);
            }
        });

        spnTrajanje.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnTrajanjeStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnDodaj))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboZadaci, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(spnTrajanje, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 166, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboZadaci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(spnTrajanje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDodaj)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed
        StavkaDnevnika stavka = new StavkaDnevnika();
        stavka.setDnevnik(dnevnik);
        stavka.setRedniBroj(dnevnik.getStavke().size() + 1);
        stavka.setZadatak((Zadatak) comboZadaci.getSelectedItem());
        stavka.setTrajanje((int) spnTrajanje.getValue());
        
        ((FormaDnevnik) roditelj).popuniTabeluStavki(new ArrayList<>(((StavkaTableModel) ((FormaDnevnik) roditelj).getTblStavke().getModel()).getStavke()));
        ((StavkaTableModel) ((FormaDnevnik) roditelj).getTblStavke().getModel()).dodajRed(stavka);
        
        ((FormaDnevnik) roditelj).popuniPodatke();
        dispose();
    }//GEN-LAST:event_btnDodajActionPerformed

    private void comboZadaciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboZadaciActionPerformed
        if (comboZadaci.getModel().getSelectedItem() != null && (int) spnTrajanje.getValue() != 0)
            btnDodaj.setEnabled(true);
        else
            btnDodaj.setEnabled(false);
    }//GEN-LAST:event_comboZadaciActionPerformed

    private void spnTrajanjeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnTrajanjeStateChanged
        if (comboZadaci.getModel().getSelectedItem() != null && (int) spnTrajanje.getValue() != 0)
            btnDodaj.setEnabled(true);
        else
            btnDodaj.setEnabled(false);
    }//GEN-LAST:event_spnTrajanjeStateChanged

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JComboBox<Zadatak> comboZadaci;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSpinner spnTrajanje;
    // End of variables declaration//GEN-END:variables

    private void popuniComboZadataka(List<Zadatak> zadaci) {
        for (Zadatak zadatak : zadaci) {
            comboZadaci.addItem(zadatak);
        }
    }
}
